version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./vuework03/Dockerfile
    ports:
      - '4000:8080'
    working_dir: /app
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
